name: nini_shop1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  # firebase hosting
  firebase_core: 
  # ui design
  gap:
  # state management
  provider: 
  # http
  http:
  # theme
  flex_color_scheme:
  #font
  google_fonts: 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
